### ISSUE TITLE
DOCUMENTATION: Research All Open AI API Responses for Errors (4xx, 5xx)

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OpenAI.NET#29]

**Comment by ElbekDeveloper** [comment]
https://github.com/openai/openai-openapi 
That's what Rami suggester reasearching

**Comment by hassanhabib** [comment]
The ask: is to find all the possible errors (especially the 4xx) so we can map them into meaningful localized exceptions: https://github.com/openai/openai-openapi

**Comment by BrianLParker** [comment]
In `.md` format list all the error codes do i need to catch when calling the OpenAI api 

Sure, here is a list of potential error codes that you might encounter when calling the OpenAI API, along with their descriptions:

HTTP Error Codes
400 Bad Request - Your request was invalid or improperly formatted.
401 Unauthorized - Your API key is invalid or missing.
403 Forbidden - You don't have permission to access this resource.
404 Not Found - The resource you're trying to access doesn't exist.
429 Too Many Requests - You've exceeded the rate limit for your account.
500 Internal Server Error - Something went wrong on the server side.
OpenAI API Error Codes
invalid_request - Your request was invalid or improperly formatted.
unauthorized - Your API key is invalid or missing.
payment_required - Your account has an outstanding balance that needs to be paid.
access_denied - You don't have permission to access this resource.
not_found - The resource you're trying to access doesn't exist.
rate_limit_exceeded - You've exceeded the rate limit for your account.
server_error - Something went wrong on the server side.
You should make sure to handle these error codes appropriately in your code to provide informative error messages to your users.

**Comment by hassanhabib** [comment]
Closing this as we've already implemented this issue.
