### ISSUE TITLE
CLIENTS: Open AI Client

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/OpenAI.NET#38]

**Comment by mabroukmahdhi** [comment]
@hassanhabib Should'nt this be closed ?

**Comment by hassanhabib** [comment]
> @hassanhabib Should'nt this be closed ?

@mabroukmahdhi yes

**Comment by mabroukmahdhi** [comment]
Closed with https://github.com/hassanhabib/OpenAI.NET/pull/59
